# Makefile

# Переменные
CC = gcc
CFLAGS = -Wall -Wextra -std=c11 -O2
TARGET = task2
SRC = task2.c
OBJ = $(SRC:.c=.o)

# Цель по умолчанию
all: $(TARGET)

# Правило для сборки исполняемого файла
$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJ)

# Правило для компиляции .c файлов в .o
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Цель для очистки скомпилированных файлов
clean:
	rm -f $(TARGET) $(OBJ)

# Дополнительная цель для пересборки
rebuild: clean all

.PHONY: all clean rebuild
